#!/bin/bash

# This script installs modules for puppet standalone

echo "[Info] Running pre-puppet.sh for install modules"

if [ "x$(dpkg -l | grep -E '^ii\s+git\s')" == "x" ]
then
    echo "[Info] Installing git"
    apt-get -y install git || (echo "[Error] Cant install git" && exit 0)
else
    echo "[Info] git already is installed, skipping"
fi

if [ "x$(gem list librarian-puppet|grep -v LOCAL)" == "x" ]
then
    echo "[Info] Installing librarian-puppet"
    gem install librarian-puppet ||
           (echo "[Error] Cant install librarian-puppet" && exit 0)
else
    echo "[Info] librarian-puppet already is installed, skipping"
fi

if [ ! -e Puppetfile ]
then

    cat > Puppetfile << EOF
#!/usr/bin/env ruby
#^syntax detection

# Warning!
# Do not edit this file, check pre-puppet.sh script!
#

forge "http://forge.puppetlabs.com"

# use dependencies defined in Modulefile
#modulefile
 mod 'puppetlabs/rabbitmq'
 mod 'saz/timezone'
 mod 'saz/locales'
 mod 'jpuppet/java-git',
      :git => "git://github.com/jpuppet/java.git"
 mod 'jfryman/nginx'
EOF

fi

mkdir -p /vagrant/vagrant.d/modules
echo "[Info] Installing puppet modules"
librarian-puppet install --path=/vagrant/vagrant.d/modules/ ||
      (echo "[Error] Cant install modules" && exit)
rm Puppetfile*

# Ugly hack for java
cp -r /vagrant/vagrant.d/modules/java-git/modules/java /vagrant/vagrant.d/modules

exit 0
